/Users/peterbanyas/Desktop/ECE 661/Project 661/ece661-GAN-project/analysis/inferencetime.py:28: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  PTH_pix2pix_UNet = torch.load("analysis/models/generator_epoch_130.pth", map_location=torch.device('cpu'))
Traceback (most recent call last):
  File "/Users/peterbanyas/Desktop/ECE 661/Project 661/ece661-GAN-project/analysis/inferencetime.py", line 56, in <module>
    image = Image.open(image_path).convert('RGB')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PIL/Image.py", line 3247, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/peterbanyas/Desktop/ECE 661/Project 661/ece661-GAN-project/analysis/analysis/data/frame_0_real.png'
